#!/bin/bash

set -e
set -o nounset
set -o pipefail

# Check for Homebrew,
# Install if we don't have it
if ! which brew >/dev/null 2>&1; then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    # Update homebrew recipes
    echo "Updating homebrew"
    brew update
fi

declare -ra BREW=(
    coreutils
    findutils
    fasd
    bash
    homebrew/dupes/grep
    git
    hub
    the_silver_searcher
    tree
    node
    python
    rename
)

echo "installing binaries"
echo "brew install ${BREW[@]}"
brew install ${BREW[@]}

if ! brew cask --version >/dev/null 2>&1; then
    echo "Installing casks"
    brew install caskroom/cask/brew-cask
else
    echo "Updating cask"
    brew cask update
fi

declare -ra CASK=(
    adium
    adobe-photoshop-lightroom
    alfred
    appcleaner
    bettertouchtool
    chicken
    colloquy
    disk-inventory-x
    dropbox
    firefox
    flux
    genymotion
    gimp
    github
    google-chrome
    google-drive
    handbrake
    hipchat
    hugin
    inkscape
    insomniax
    intellij-idea
    iterm2
    keepassx
    logitech-unifying
    logitech-control-center
    luminance-hdr
    pycharm-ce
    qlcolorcode
    qlmarkdown
    skype
    slate
    sourcetree
    spotify
    steam
    transmission
    transmit
    vagrant
    virtualbox
    vlc
    wireshark
    x2goclient
)

echo "brew cask install ${CASK[@]}"
brew cask install ${CASK[@]}

brew cask alfred link

brew tap caskroom/fonts

declare -ra FONTS=(
    font-roboto
)

echo "installing fonts..."
echo "brew cask install ${FONTS[@]}"
brew cask install ${FONTS[@]}
